name: Publish ConsoleHelpers
on:
  push:
    tags:
      - 'ConsoleHelpers/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      run: echo ::set-env name=RELEASE_VERSION::$(echo $GITHUB_REF | cut -d v -f 2)
    - name: Checkout master
      uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build and pack nuget 
      run: #|
        dotnet pack ./src/ConsoleHelpers/ConsoleHelpers.csproj -c Release -o NuGetPackages /p:Version=$RELEASE_VERSION
        #dotnet pack ./src/KeyValueHelpers/KeyValueHelpers.csproj -c Release -o NuGetPackages /p:Version=$RELEASE_VERSION
    - name: Publish to MyGet
      env:
        MYGET_SOURCE: https://www.myget.org/F/totopolis/api/v3/index.json
      run: #|
        dotnet nuget push ./NuGetPackages/ConsoleHelpers.$RELEASE_VERSION.nupkg -k ${{ secrets.MYGET_APIKEY }} -s $MYGET_SOURCE
        #dotnet nuget push ./NuGetPackages/KeyValueHelpers.$RELEASE_VERSION.nupkg -k ${{ secrets.MYGET_APIKEY }} -s $MYGET_SOURCE